### ISSUE TITLE
Compiling on Rocky 9

### ISSUE THREAD

**Issue by skarone** [OpenAssetIO/OpenAssetIO#1350]
Hi, 
I'm trying to compile it (to use it in the usdOpenAssetIOResolver) for Rocky 9.
I cloned and compiled each dependency, but I can't find a way to get the linking working.
I also tried to use the docker way, which is compiling.. but after trying to use the usdOpenAssetIOResolver, I get the same linking error.

Any help or guidance would be much appreciated!

This is the error I'm getting:
```
[100%] Linking CXX shared module ../../../lib/python3.9/site-packages/openassetio/_openassetio.cpython-39-x86_64-linux-gnu.so
Generating .pyi stubs with pybind11-stubgen...
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nacio/.local/lib/python3.9/site-packages/pybind11_stubgen/__main__.py", line 4, in <module>
    main()
  File "/home/nacio/.local/lib/python3.9/site-packages/pybind11_stubgen/__init__.py", line 319, in main
    run(
  File "/home/nacio/.local/lib/python3.9/site-packages/pybind11_stubgen/__init__.py", line 358, in run
    QualifiedName.from_str(module_name), importlib.import_module(module_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /home/nacio/Documents/OpenAssetIO/build/lib64/libopenassetio.so.1.0: undefined symbol: _ZN3ada7unicode14percent_encodeILb0EEEbSt17basic_string_viewIcSt11char_traitsIcEEPKhRSs
gmake[2]: *** [src/openassetio-python/cmodule/CMakeFiles/openassetio-python-module.dir/build.make:520: lib/python3.9/site-packages/openassetio/_openassetio.cpython-39-x86_64-linux-gnu.so] Error 1
gmake[2]: *** Deleting file 'lib/python3.9/site-packages/openassetio/_openassetio.cpython-39-x86_64-linux-gnu.so'
gmake[1]: *** [CMakeFiles/Makefile2:341: src/openassetio-python/cmodule/CMakeFiles/openassetio-python-module.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Here is the script I used to build everything:
```
git clone --branch v3.2.0 https://github.com/marzer/tomlplusplus
# $(pwd)/<dependency>/dist is the install dir
cd tomlplusplus && cmake -S . -B build --install-prefix $(pwd)/dist && cmake --build build && cmake --install build && cd ..
git clone --branch v42 https://github.com/rollbear/trompeloeil
cd trompeloeil && cmake -S . -B build --install-prefix $(pwd)/dist && cmake --build build && cmake --install build && cd ..
git clone --branch 9.1.0 https://github.com/fmtlib/fmt
cd fmt && cmake -S . -B build --install-prefix $(pwd)/dist -DFMT_MASTER_PROJECT=OFF -DFMT_INSTALL=ON && \
    cmake --build build --parallel && cmake --install build && cd ..
git clone --branch v2.7.4 https://github.com/ada-url/ada
cd ada && cmake -S . -B build --install-prefix $(pwd)/dist -DBUILD_SHARED_LIBS="OFF" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DADA_TESTING=OFF && \
    cmake --build build --parallel && cmake --install build && cd ..
git clone --branch pcre2-10.42 https://github.com/PCRE2Project/pcre2
cd pcre2 && cmake -S . -B build --install-prefix $(pwd)/dist \
    -DPCRE2_STATIC_PIC=ON -DPCRE2_SUPPORT_JIT=ON -DPCRE2_BUILD_PCRE2GREP=OFF \
    -DPCRE2_BUILD_TESTS=OFF && \
    cmake --build build --parallel && cmake --install build && cd ..
git clone https://github.com/pybind/pybind11.git
cd pybind11 && cmake -S . -B build --install-prefix $(pwd)/dist &&\
    cmake --build build --parallel && cmake --install build && cd ..
git clone https://github.com/OpenAssetIO/OpenAssetIO.git
cd OpenAssetIO && \
    cmake -S . -B build --install-prefix $(pwd)/dist -DCMAKE_PREFIX_PATH="/home/nacio/Documents/tomlplusplus/dist;/home/nacio/Documents/trompeloeil/dist;/home/nacio/Documents/fmt/dist;/home/nacio/Documents/ada/dist;/home/nacio/Documents/pcre2/dist;/home/nacio/Documents/pybind11/dist" && \
    cmake --build build && cmake --install build && cd ..
```

Thanks a lot

**Comment by feltech** [comment]
Consolidated some issues into a broader epic re. better supporting CY23+ in https://github.com/OpenAssetIO/OpenAssetIO/issues/1351

**Comment by skarone** [comment]
Hi @feltech,
Thanks a lot for the quick feedback, using USE_CXX11 did the trick!!

I will follow the CY23 ticket, we will probably need this.

Thanks a lot again!

**Comment by feltech** [comment]
:+1: It would be great to hear about your use-case and/or feedback more generally, if you have the opportunity. You can always reach out [here on GitHub](https://github.com/OpenAssetIO/OpenAssetIO/discussions), the ASWF [#openassetio Slack channel](https://academysoftwarefdn.slack.com/archives/C03Q36QS8N4), or [the mailing list](https://lists.aswf.io/g/openassetio-discussion).

In the meantime, I'll close this issue.
